script:
  - 'bundle exec rspec'

env:
  - 'SENDGRID_PASSWORD=123 SENDGRID_USERNAME=123 DEVISE_SECRET_KEY=123 SECRET_TOKEN=123'
branches:
  only:
    - master
rvm:
  - 2.3.1
services:
  - mongodb

before_install:
 - gem update bundler
